"""Representative model catalog, including older models; not a complete lineup.

Vehicle types are selected separately and are not stored in this catalog.
For a different body style, choose 'Other / not listed' and set the type manually.
"""
MODELS = {
    'Toyota': [
        '4Runner', '86', 'Avalon', 'bZ4X', 'C-HR', 'Camry', 'Celica', 'Corolla',
        'Corolla Cross', 'Corolla Hatchback', 'Crown', 'FJ Cruiser', 'GR86',
        'GR Corolla', 'GR Supra', 'Highlander', 'Land Cruiser', 'Matrix',
        'Mirai', 'MR2', 'Prius', 'Prius c', 'Prius Prime', 'RAV4', 'Sequoia',
        'Sienna', 'Supra', 'Tacoma', 'T100', 'Tundra', 'Venza', 'Yaris',
    ],
    'Honda': [
        'Accord', 'Civic', 'Civic Coupe', 'Civic Hatchback', 'Civic Type R',
        'Clarity', 'CR-V', 'CR-Z', 'Crosstour', 'Element', 'Fit', 'HR-V',
        'Insight', 'Odyssey', 'Passport', 'Pilot', 'Prelude', 'Prologue',
        'Ridgeline', 'S2000', ' del Sol',
    ],
    'Ford': [
        'Bronco', 'Bronco Sport', 'C-MAX', 'Crown Victoria', 'E-Series',
        'EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150',
        'F-250 Super Duty', 'F-350 Super Duty', 'F-450 Super Duty', 'Fiesta',
        'Flex', 'Focus', 'Fusion', 'GT', 'Maverick', 'Model T', 'Mustang',
        'Mustang Mach-E', 'Ranger', 'Taurus', 'Transit', 'Transit Connect',
    ],
    'Chevrolet': [
        'Avalanche', 'Aveo', 'Blazer', 'Bolt EV', 'Bolt EUV', 'Camaro', 'Cobalt',
        'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Express', 'HHR', 'Impala',
        'Malibu', 'Monte Carlo', 'Prizm', 'S-10', 'Silverado 1500',
        'Silverado 2500HD', 'Silverado 3500HD', 'Sonic', 'Spark', 'Suburban',
        'Tahoe', 'Trailblazer', 'Traverse', 'Trax', 'Uplander', 'Venture',
    ],
    'Nissan': [
        '350Z', '370Z', 'Altima', 'Armada', 'Cube', 'Frontier', 'GT-R', 'Juke',
        'Kicks', 'Leaf', 'Maxima', 'Murano', 'NV', 'NV200', 'Pathfinder',
        'Quest', 'Rogue', 'Rogue Sport', 'Sentra', 'Stanza', 'Titan', 'Versa',
        'Xterra', 'Z',
    ],
    'Hyundai': [
        'Accent', 'Azera', 'Elantra', 'Elantra GT', 'Entourage', 'Equus',
        'Genesis Coupe', 'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Nexo',
        'Palisade', 'Santa Cruz', 'Santa Fe', 'Scoupe', 'Sonata', 'Tiburon',
        'Tucson', 'Veloster', 'Venue', ' Veracruz',
    ],
    'Kia': [
        'Amanti', 'Cadenza', 'Carnival', 'EV6', 'Forte', 'K5', 'K900', 'Niro',
        'Optima', 'Rio', 'Rondo', 'Sedona', 'Seltos', 'Soul', 'Spectra',
        'Sportage', 'Stinger', 'Telluride',
    ],
    'Mazda': [
        '2', '3', '5', '6', '626', 'B-Series', 'CX-3', 'CX-30', 'CX-5', 'CX-50',
        'CX-7', 'CX-9', 'CX-90', 'Mazda3', 'Mazda5', 'Mazda6', 'Millenia',
        'MPV', 'MX-3', 'MX-5 Miata', 'MX-30', 'RX-7', 'RX-8', 'Tribute', '929',
    ],
    'Subaru': [
        'Ascent', 'Baja', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Justy',
        'Legacy', 'Outback', 'SVX', 'Tribeca', 'WRX', 'WRX STI', 'XT',
    ],
    'Volkswagen': [
        'Arteon', 'Atlas', 'Atlas Cross Sport', 'Beetle', 'CC', 'Corrado',
        'Eos', 'EuroVan', 'Golf', 'Golf GTI', 'Golf R', 'ID.4', 'ID.7',
        'Jetta', 'Jetta GLI', 'Passat', 'Phaeton', 'Routan', 'Tiguan',
        'Touareg', 'Transporter', 'Vanagon',
    ],
    'Jeep': [
        'Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee',
        'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade', 'Wagoneer',
        'Wagoneer S', 'Wrangler',
    ],
    'Ram': ['1500', '1500 Classic', '2500', '3500', '4500', '5500', 'Dakota', 'ProMaster', 'ProMaster City'],
    'GMC': ['Acadia', 'Canyon', 'Envoy', 'Hummer EV', 'Jimmy', 'Safari', 'Savana', 'Sierra 1500', 'Sierra 2500HD', 'Sierra 3500HD', 'Sonoma', 'Terrain', 'Typhoon', 'Yukon', 'Yukon XL'],
    'Buick': ['Cascada', 'Century', 'Enclave', 'Encore', 'Encore GX', 'Envision', 'LaCrosse', 'LeSabre', 'Lucerne', 'Park Avenue', 'Rainier', 'Regal', 'Rendezvous', 'Riviera', 'Skylark', 'Verano'],
    'Mitsubishi': ['3000GT', 'Eclipse', 'Eclipse Cross', 'Endeavor', 'Galant', 'Lancer', 'Mirage', 'Montero', 'Outlander', 'Outlander Sport', 'Raider'],
    'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'M2', 'M3', 'M4', 'M5', 'M8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z3', 'Z4', 'Z8'],
    'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'EQS', 'EQB', 'EQE', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLK', 'GLS', 'M-Class', 'Maybach', 'S-Class', 'SL', 'SLC', 'SLK', 'Sprinter', 'V-Class'],
    'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'e-tron GT', 'Q3', 'Q4 e-tron', 'Q5', 'Q6 e-tron', 'Q7', 'Q8', 'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'TT'],
    'Lexus': ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LFA', 'LM', 'LS', 'LX', 'NX', 'RC', 'RX', 'RZ', 'SC', 'UX'],
    'Acura': ['CL', 'CSX', 'ILX', 'Integra', 'Legend', 'MDX', 'NSX', 'RDX', 'RL', 'RLX', 'RSX', 'SLX', 'TL', 'TLX', 'TSX', 'ZDX'],
    'Infiniti': ['EX', 'FX', 'G20', 'G35', 'G37', 'I30', 'J30', 'JX', 'M35', 'M37', 'Q30', 'Q40', 'Q45', 'Q50', 'Q60', 'Q70', 'QX4', 'QX30', 'QX50', 'QX55', 'QX56', 'QX60', 'QX80'],
    'Genesis': ['Coupe', 'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
    'Volvo': ['240', '740', '850', 'C30', 'C40', 'C70', 'EX30', 'EX90', 'S40', 'S60', 'S70', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'XC40', 'XC60', 'XC70', 'XC90'],
    'Cadillac': ['ATS', 'CT4', 'CT5', 'CT6', 'CTS', 'DeVille', 'DTS', 'Eldorado', 'Escalade', 'Lyriq', 'Seville', 'SRX', 'STS', 'XT4', 'XT5', 'XT6', 'XTS'],
    'Lincoln': ['Aviator', 'Blackwood', 'Continental', 'Corsair', 'LS', 'MKC', 'MKS', 'MKT', 'MKX', 'MKZ', 'Nautilus', 'Navigator', 'Town Car', 'Zephyr'],
    'Tesla': ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
    'Polestar': ['Polestar 1', 'Polestar 2', 'Polestar 3', 'Polestar 4', 'Polestar 5', 'Polestar 6'],
    'Porsche': ['718 Boxster', '718 Cayman', '911', '918 Spyder', '924', '928', '944', '959', '968', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
    'Jaguar': ['E-PACE', 'F-PACE', 'F-TYPE', 'I-PACE', 'S-Type', 'X-TYPE', 'XE', 'XF', 'XJ', 'XK'],
    'Maserati': ['Biturbo', 'Ghibli', 'GranCabrio', 'GranTurismo', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
    'Bentley': ['Arnage', 'Azure', 'Bentayga', 'Continental GT', 'Continental Flying Spur', 'Flying Spur', 'Mulsanne'],
    'Ferrari': ['296 GTB', '296 GTS', '348', '360 Modena', '458 Italia', '488 GTB', '512', '550 Maranello', '575M', '612 Scaglietti', '812 Superfast', 'California', 'Dino', 'Enzo', 'F8 Tributo', 'F12berlinetta', 'LaFerrari', 'Portofino', 'Roma', 'SF90 Stradale', 'Testarossa'],
    'Lamborghini': ['Aventador', 'Countach', 'Diablo', 'Gallardo', 'Huracan', 'Jalpa', 'Miura', 'Murcielago', 'Revuelto', 'Urus', 'Veneno'],
    'Aston Martin': ['DB7', 'DB9', 'DB11', 'DB12', 'DBS', 'DBX', 'Rapide', 'V8 Vantage', 'V12 Vantage', 'Vanquish', 'Virage'],
    'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Silver Cloud', 'Silver Shadow', 'Silver Spirit', 'Wraith'],
    'Acura': ['CL', 'CSX', 'ILX', 'Integra', 'Legend', 'MDX', 'NSX', 'RDX', 'RL', 'RLX', 'RSX', 'SLX', 'TL', 'TLX', 'TSX', 'ZDX'],
    'Chrysler': ['200', '300', 'Aspen', 'Concorde', 'Crossfire', 'Grand Voyager', 'Imperial', 'LHS', ' Pacifica', 'PT Cruiser', 'Sebring', 'Town & Country', 'Voyager'],
    'Dodge': ['Avenger', 'Caliber', 'Challenger', 'Charger', 'Dart', 'Dakota', 'Durango', 'Grand Caravan', 'Hornet', 'Journey', 'Magnum', 'Neon', 'Nitro', 'Ram', 'Viper'],
    'Pontiac': ['Aztek', 'Bonneville', 'Fiero', 'Firebird', 'G5', 'G6', 'Grand Am', 'Grand Prix', 'Montana', 'Solstice', 'Sunfire', 'Torrent', 'Trans Am', 'Vibe'],
    'Saturn': ['Aura', 'Ion', 'L-Series', 'Outlook', 'Relay', 'Sky', 'Vue'],
    'Oldsmobile': ['Alero', 'Aurora', 'Bravada', 'Cutlass', 'Intrigue', 'Silhouette'],
    'Hummer': ['H1', 'H2', 'H3', 'EV'],
    'Fiat': ['124 Spider', '500', '500L', '500X', 'Bravo', 'Punto', '124 Sport Spider'],
    'Alfa Romeo': ['4C', 'Giulia', 'Giulietta', 'GTV', 'MiTo', 'Stelvio', 'Tonale'],
    'Mini': ['Clubman', 'Cooper', 'Countryman', 'Coupe', 'Paceman', 'Roadster'],
    'Lotus': ['Elise', 'Emira', 'Esprit', 'Evora', 'Exige'],
    'McLaren': ['570S', '570GT', '600LT', '650S', '675LT', '720S', '750S', '765LT', 'Artura', 'GT', 'P1', 'Senna'],
    'Rivian': ['R1S', 'R1T', 'R2', 'R3', 'R3X'],
    'Lucid': ['Air', 'Gravity'],
    'BYD': ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Tang'],
    'Suzuki': ['Equator', 'Forenza', 'Kizashi', 'Samurai', 'Sidekick', 'SX4', 'Swift', 'Vitara', 'XL7'],
    'Isuzu': ['Amigo', 'Ascender', 'Axiom', 'Hombre', 'i-280', 'i-350', 'Rodeo', 'Trooper', 'VehiCROSS'],
    'Saab': ['9-2X', '9-3', '9-4X', '9-5', '9-7X', '900', '9000'],
}
