"""Representative model catalog, including older models; not a complete lineup.

Vehicle types are selected separately and are not stored in this catalog.
For a different body style, choose 'Other / not listed' and set the type manually.
"""
MODELS = {
    'Toyota': ['Camry', 'RAV4', 'Sienna'],
    'Honda': ['Accord', 'CR-V', 'Odyssey'],
    'Ford': ['Mustang Coupe', 'Explorer', 'F-150'],
    'Chevrolet': ['Malibu', 'Tahoe', 'Silverado 1500'],
    'Nissan': ['Altima', 'Rogue', 'Frontier'],
    'Hyundai': ['Elantra', 'Tucson', 'Palisade'],
    'Kia': ['K5', 'Sportage', 'Carnival'],
    'Mazda': ['Mazda3 Sedan', 'CX-5', 'CX-9'],
    'Subaru': ['Legacy', 'Forester', 'Outback'],
    'Volkswagen': ['Jetta', 'Golf GTI', 'Atlas'],
    'Jeep': ['Wrangler', 'Grand Cherokee', 'Gladiator'],
    'Ram': ['1500', '2500', 'ProMaster'],
    'GMC': ['Sierra 1500', 'Yukon', 'Acadia'],
    'Buick': ['Enclave', 'Envision', 'Encore GX'],
    'Mitsubishi': ['Outlander', 'Eclipse Cross', 'Mirage'],
    'BMW': ['3 Series Sedan', 'X3', 'X5'],
    'Mercedes-Benz': ['C-Class Sedan', 'GLC SUV', 'Sprinter'],
    'Audi': ['A4 Sedan', 'Q5', 'Q7'],
    'Lexus': ['ES', 'RX', 'GX'],
    'Acura': ['TLX', 'RDX', 'MDX'],
    'Infiniti': ['Q50', 'QX60', 'QX80'],
    'Genesis': ['G70', 'G80', 'GV80'],
    'Volvo': ['S60', 'V60', 'XC90'],
    'Cadillac': ['CT4', 'CT5', 'Escalade'],
    'Lincoln': ['Corsair', 'Aviator', 'Navigator'],
    'Tesla': ['Model 3', 'Model Y', 'Cybertruck'],
    'Polestar': ['Polestar 2', 'Polestar 3', 'Polestar 4'],
    'Porsche': ['911 Coupe', 'Macan', 'Cayenne'],
    'Land Rover': ['Defender', 'Discovery', 'Range Rover Sport'],
    'Jaguar': ['XE', 'XF Sedan', 'F-PACE'],
    'Maserati': ['Ghibli', 'Levante', 'Grecale'],
    'Bentley': ['Flying Spur', 'Continental GT Coupe', 'Bentayga'],
    'Ferrari': ['Roma Coupe', '296 GTB', 'Purosangue'],
    'Lamborghini': ['Huracan Coupe', 'Revuelto', 'Urus'],
    'Aston Martin': ['DB11 Coupe', 'DB12 Coupe', 'DBX'],
    'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan'],
}
